# Menus
menu:
  Home: .
  Archives: archives
  Categories: categories
  Tags: tags
  About: about

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: images/logo.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: css/images/avatar.png
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: leonardmac
        author_title: 工科狗
        location: 中国 上海 #ShangHai, China
        follow: https://github.com/leonardmac0614/
    highlight: monokai
    sidebar: right # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: /favicon.ico # path to favicon
    social_links:
        github: http://github.com/leonardmac0614/
        twitter: http://twitter.com/leonard_mac0614
        weibo: http://weibo.com/leonardmac
        rss: /
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: # enter disqus shortname here
    duoshuo: leonardmac # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: jiathis # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: eaf5895b4d7cf083ca944235170db342# enter Baidu Analytics hash key
    
# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Hexo: http://leonardmac.me
